### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by anibalsanchez** [TLWebdesign/Joomla-3.10.12-languagehelper-hotfix#1]
Hi,

**No genuine problem here! Just wanted to extend my gratitude for all your hard work!** 👏👏👏

Best Regards,

**Comment by TLWebdesign** [comment]
Hi, thanks for your kind words altho it was not much work and i learned how to write file plugins  😃

**Comment by grantg182** [comment]
Ditto. Doing God's work here Tom. Thanks!

**Comment by TLWebdesign** [comment]
Thanks but the Joomla Security Strike Team are the hero's here in always fixing these vulnerabilities. I just took what was there and made it installable.

**Comment by Elfangor93** [comment]
Thank you for this great service!!
